<<<<<<< HEAD
import Head from 'next/head'
import Image from 'next/image'
import Whiteboard from '../components/whiteboard'
import styles from '../styles/Home.module.css'
// import App from '../components/whiteboardTwo'

export default function Home() {
  return (
    <div >
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
=======
import Head from '../components/Head'
import Header from '../components/Header'
import Main from '../components/Main'
import Footer from '../components/Footer'
import { useState } from 'react'


export default function Home() {

  const [title,setTitle] = useState('kuro space');
  return (
    <div className="bg-white shadow">
      <Head title={title}/>
      <Header header={title}/>
      <Main title={title} />
      <Footer />
>>>>>>> 1b9e8fad54beff8f390fc26e8e21d62f09020118
    </div>
  )
}
